kitties = {
    "laura": {"breed": "british white",
              "personality": "troubled, but lovable.",
              "treasure": "ring from the black lodge",
              "hint": "fire walk with me",
              "future": "you travel to an alternate universe together and kill Bob. Laura becomes a therapist dealing with sexual trauma."},
    "tor": {"breed": "ginger housecat",
            "personality": "has never been seen without his sunglasses and a beanie.",
            "treasure": "usb drive",
            "hint": "a modern device",
            "future": "you and Tor develop a web browser for cats together. you become rich and move to california."},
    "tony": {"breed": "black persian",
             "personality": "drama queen and a writer. queerer than you.",
             "treasure": "iris flower",
             "hint": "something tender and violet",
             "future": "Tony writes a revolutionary novel about love and sexuality in the cat community. together you move to Sweden."},
    "wanda": {"breed": "siberian tabby",
              "personality": "wears hats unironically.",
              "treasure": "lilac scarf",
              "hint": "something you wear around your neck",
              "future": "Wanda becomes a plus-size model and you - a famous photographer. you live together on a villa in Spain and drink margaritas at noon."},
    "piper": {"breed": "golden chinchilla scottish fold",
              "personality": "pretends she is straight, is not.",
              "treasure": "toothbrush",
              "hint": "can be used to stab a bitch",
              "future": "Piper leaves you only to marry her ex-girlfriend. you get invited to their wedding and make a scandal there. you drink to forget for some time, but eventually start dating other kitties."},
    "carrie": {"breed": "natural mink housecat",
               "personality": "smokes marlboro golds.",
               "treasure": "hair clip",
               "hint": "something for your curls",
               "future": "Carrie stops smoking cigs and buys a vape pen. you move to Brooklyn together and open a small family business."},
    "mogg": {"breed": "russian blue",
             "personality": "adventurous stoner.",
             "treasure": "half a doobie",
             "hint": "420",
             "future": "you and Mogg open a coffeeshop in Netherlands. everything goes great until he moves onto the hard drugs. Mogg dies of fentanyl overdose."},
    "summer": {"breed": "ebony housecat",
               "personality": "goth af.",
               "treasure": "rat scull",
               "hint": "is it still alive?",
               "future": "you and Summer invent a reusable coffin and get paid for it. you buy a haunted house somewhere in the countryside and live happily ever after."},
    "anthony": {"breed": "chocolate point siamese",
                "personality": "mafia boss with the softest heart.",
                "treasure": "four-leaved clover",
                "hint": "somebody's a lucky bastard",
                "future": "you and Anthony live in a mansion in New Jersey with two kids. you know there's someone on the side, but keep quiet about it. one day he sees ducks in your pool and decides to go to therapy."},
    "marshmallow": {"breed": "white housecat",
                    "personality": "a witch. eats organic and sweats glitter.",
                    "treasure": "meteor",
                    "hint": "it fell from the sky",
                    "future": ""},
}
