kitties = {
    "laura": {"breed": "british white",
              "personality": "troubled, but lovable.",
              "treasure": "ring from the black lodge",
              "hint": "",
              "future": ""},
    "tor": {"breed": "ginger housecat",
            "personality": "has never been seen without his sunglasses and a beanie.",
            "treasure": "usb drive",
            "hint": "",
            "future": ""},
    "tony": {"breed": "black persian",
             "personality": "drama queen and a writer. queerer than you.",
             "treasure": "iris flower",
             "hint": "",
             "future": ""},
    "wanda": {"breed": "siberian tabby",
              "personality": "wears hats unironically.",
              "treasure": "lilac scarf",
              "hint": "",
              "future": ""},
    "piper": {"breed": "golden chinchilla scottish fold",
              "personality": "pretends she is straight, is not.",
              "treasure": "toothbrush",
              "hint": "",
              "future": ""},
    "carrie": {"breed": "natural mink housecat",
               "personality": "smokes marlboro golds.",
               "treasure": "hair clip",
               "hint": "",
               "future": ""},
    "mogg": {"breed": "russian blue",
             "personality": "adventurous stoner.",
             "treasure": "half a doobie",
             "hint": "",
             "future": ""},
    "summer": {"breed": "ebony housecat",
               "personality": "goth af.",
               "treasure": "rat scull",
               "hint": "",
               "future": ""},
    "anthony": {"breed": "chocolate point siamese",
                "personality": "mafia boss with the softest heart.",
                "treasure": "four-leaved clover",
                "hint": "",
                "future": ""},
    "marshmallow": {"breed": "white housecat",
                    "personality": "a witch. eats organic and sweats glitter.",
                    "treasure": "meteor",
                    "hint": "",
                    "future": ""},
}
